
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 22tarpat
 */
public class AddPatientScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddPatientScreen
     */
    public AddPatientScreen() {
        initComponents();
        //Hiding the medical aid components upon form initialization, components should only be visible if the radio button is selected
        lblMedAid.setVisible(false);
        lblMedAidNum.setVisible(false);
        txtMedAid.setVisible(false);
        txtMedAidNum.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAddPatient = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblIDNumber = new javax.swing.JLabel();
        txtIDNum = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        labelSurname = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        lblMedAid = new javax.swing.JLabel();
        txtMedAid = new javax.swing.JTextField();
        lblMedAidNum = new javax.swing.JLabel();
        txtMedAidNum = new javax.swing.JTextField();
        btnRecordPatient = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblMedicalHistory = new javax.swing.JLabel();
        scrPaneMedHistory = new javax.swing.JScrollPane();
        txtMedHistory = new javax.swing.JTextArea();
        lblRBNMedAid = new javax.swing.JLabel();
        rbnMedAid = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeading.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblHeading.setText("Add Patient");

        lblIDNumber.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblIDNumber.setText("Legal ID Number:");

        txtIDNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDNumActionPerformed(evt);
            }
        });

        lblFirstName.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblFirstName.setText("First Name:");

        labelSurname.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        labelSurname.setText("Surname:");

        lblMedAid.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblMedAid.setText("Medical Aid:");

        lblMedAidNum.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblMedAidNum.setText("Medical Aid Number:");

        btnRecordPatient.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnRecordPatient.setText("Record Patient");
        btnRecordPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordPatientActionPerformed(evt);
            }
        });

        btnHelp.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblMedicalHistory.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblMedicalHistory.setText("Medical history:");

        txtMedHistory.setColumns(20);
        txtMedHistory.setLineWrap(true);
        txtMedHistory.setRows(5);
        scrPaneMedHistory.setViewportView(txtMedHistory);

        lblRBNMedAid.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblRBNMedAid.setText("<html>Does the patient have<br/>medical aid?</html>");

        rbnMedAid.setText("Yes");
        rbnMedAid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnMedAidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddPatientLayout = new javax.swing.GroupLayout(pnlAddPatient);
        pnlAddPatient.setLayout(pnlAddPatientLayout);
        pnlAddPatientLayout.setHorizontalGroup(
            pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddPatientLayout.createSequentialGroup()
                        .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIDNumber)
                            .addComponent(lblFirstName)
                            .addComponent(labelSurname)
                            .addComponent(lblMedicalHistory))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrPaneMedHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                            .addComponent(txtSurname)
                            .addComponent(txtFirstName)
                            .addComponent(txtIDNum)))
                    .addGroup(pnlAddPatientLayout.createSequentialGroup()
                        .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeading)
                            .addGroup(pnlAddPatientLayout.createSequentialGroup()
                                .addComponent(lblRBNMedAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(rbnMedAid))
                            .addGroup(pnlAddPatientLayout.createSequentialGroup()
                                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnRecordPatient))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlAddPatientLayout.createSequentialGroup()
                        .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedAidNum)
                            .addComponent(lblMedAid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedAid)
                            .addComponent(txtMedAidNum))))
                .addGap(71, 71, 71))
        );
        pnlAddPatientLayout.setVerticalGroup(
            pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddPatientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading)
                .addGap(30, 30, 30)
                .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDNumber)
                    .addComponent(txtIDNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSurname)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedicalHistory)
                    .addComponent(scrPaneMedHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRBNMedAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbnMedAid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedAid)
                    .addComponent(txtMedAid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedAidNum)
                    .addComponent(txtMedAidNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRecordPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddPatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHelp)
                    .addComponent(btnBack))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDNumActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        //This code takes the user to the help screen
        this.setVisible(false);
        new HelpScreen().setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //This code takes the user back to the main Patients screen
        this.setVisible(false);
        new PatientsScreen().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRecordPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordPatientActionPerformed
        //The following code is used to extract the user's input data, and through the .addPatient() method, the data is added to tblPatients

        //Extracting user data input
        String IDNum = txtIDNum.getText();
        String fName = txtFirstName.getText();
        String sName = txtSurname.getText();
        String medHis = txtMedHistory.getText();
        
        //Determining if the patient to be added has medical aid or not
        if (rbnMedAid.isSelected()) 
        {
            //Creating a MedicalAid object because the user selected the radio button
            String medAid = txtMedAid.getText();
            String medAidNum = txtMedAidNum.getText();
            MedicalAid medAidPatObj = new MedicalAid(IDNum, fName, sName, medHis, medAid, medAidNum);
            //Using the .addPatient() method to capture the user input data and insert it into tblPatient
            medAidPatObj.addPatient();
        }
        else
        {
            //Creating a Patient object because the user did not select the radio buutton
            Patient patObj = new Patient(IDNum, fName, sName, medHis);
            //Using the .addPatient() method to capture user input data and insert it into tblPatient
            patObj.addPatient();
        }
    }//GEN-LAST:event_btnRecordPatientActionPerformed

    private void rbnMedAidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnMedAidActionPerformed
        //code to make the components relevant to medical aid capture visible depending on whether or not the radio button is selected
        if (rbnMedAid.isSelected())
        {
            lblMedAid.setVisible(true);
            lblMedAidNum.setVisible(true);
            txtMedAid.setVisible(true);
            txtMedAidNum.setVisible(true);
        }
        else
        {
            lblMedAid.setVisible(false);
            lblMedAidNum.setVisible(false);
            txtMedAid.setVisible(false);
            txtMedAidNum.setVisible(false);
        }
    }//GEN-LAST:event_rbnMedAidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatientScreen().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnRecordPatient;
    private javax.swing.JLabel labelSurname;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblIDNumber;
    private javax.swing.JLabel lblMedAid;
    private javax.swing.JLabel lblMedAidNum;
    private javax.swing.JLabel lblMedicalHistory;
    private javax.swing.JLabel lblRBNMedAid;
    private javax.swing.JPanel pnlAddPatient;
    private javax.swing.JRadioButton rbnMedAid;
    private javax.swing.JScrollPane scrPaneMedHistory;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtIDNum;
    private javax.swing.JTextField txtMedAid;
    private javax.swing.JTextField txtMedAidNum;
    private javax.swing.JTextArea txtMedHistory;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
