
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author taran
 */
public class HelpScreen extends javax.swing.JFrame {

    /**
     * Creates new form HelpScreen
     */
    public HelpScreen() {
        initComponents();
        //the following code extracts the FAQ from a text file, and then populates the text area with this data
        String output = "";
        try {
            Scanner scFile = new Scanner(new File("Help.txt"));
            while (scFile.hasNext())
            {
                Scanner scLine = new Scanner(scFile.nextLine()).useDelimiter("#");
                String question = scLine.next();
                String answer = scLine.next();
                String questionAndAnswer = "Question: " + question + "\nAnswer: " + answer;
                output = output + questionAndAnswer + "\n\n";
            }
            txtFAQ.setText(output);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HelpScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHelpScreen = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        scrPaneFAQ = new javax.swing.JScrollPane();
        txtFAQ = new javax.swing.JTextArea();
        lblCredit = new javax.swing.JLabel();
        lblFurtherQuestions = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        lblHeading.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblHeading.setText("Help");

        txtFAQ.setEditable(false);
        txtFAQ.setColumns(20);
        txtFAQ.setLineWrap(true);
        txtFAQ.setRows(5);
        scrPaneFAQ.setViewportView(txtFAQ);

        lblCredit.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblCredit.setText("Developed by Taran Patel");

        lblFurtherQuestions.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblFurtherQuestions.setText("If you have any further questions, please contact me here:");

        lblPhone.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblPhone.setText("Phone: 072 327 8291");

        lblEmail.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblEmail.setText("E-mail: patel.taran10@gmail.com");

        btnBack.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHelpScreenLayout = new javax.swing.GroupLayout(pnlHelpScreen);
        pnlHelpScreen.setLayout(pnlHelpScreenLayout);
        pnlHelpScreenLayout.setHorizontalGroup(
            pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                .addGroup(pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrPaneFAQ))
                    .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(lblHeading)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                                .addGroup(pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCredit)
                                    .addComponent(lblFurtherQuestions))
                                .addGap(0, 283, Short.MAX_VALUE))
                            .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                                .addGroup(pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblPhone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack)))))
                .addContainerGap())
        );
        pnlHelpScreenLayout.setVerticalGroup(
            pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrPaneFAQ, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnlHelpScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlHelpScreenLayout.createSequentialGroup()
                        .addComponent(lblCredit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFurtherQuestions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail))
                    .addComponent(btnBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHelpScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHelpScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        //This code takes the user back to the welcome screen
        this.setVisible(false);
        new WelcomeScreen().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblCredit;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFurtherQuestions;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JPanel pnlHelpScreen;
    private javax.swing.JScrollPane scrPaneFAQ;
    private javax.swing.JTextArea txtFAQ;
    // End of variables declaration//GEN-END:variables
}
